config/routes.rb
Sauba::Application.routes.draw do

  match 'issues'        => 'home#issues',       :via => :get
  match 'about_us'      => 'home#about_us',     :via => :get
  match 'get_involved'  => 'home#get_involved', :via => :get

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end

  def issues
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<h1>About us</h1>
<p>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ornare eros. Duis nisl ligula, aliquam eget bibendum eu, fermentum id lorem. Etiam cursus enim quis arcu ultrices, vitae ultricies nulla eleifend. Suspendisse eu dignissim massa. Cras ac velit urna. Ut ut ante placerat, porta velit et, dapibus elit. Ut vehicula enim purus, non semper quam posuere nec. Donec et ultricies arcu. Aenean vitae purus massa. Aenean euismod pharetra magna, ac fringilla quam fermentum non. Donec ut turpis vel lorem fringilla vulputate in nec velit.
</p>
<br/>
<p>
	Fusce commodo massa ante, vitae bibendum turpis dignissim ac. Vivamus sed tellus et magna vulputate aliquam quis tristique lacus. Proin condimentum volutpat purus nec tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse pretium a nisl et hendrerit. Sed sagittis lectus at mi hendrerit porta. Vivamus fermentum eleifend nunc, vel vestibulum lorem pulvinar non. Integer tristique pellentesque lacinia. Proin quam sapien, dapibus nec posuere eget, molestie in diam. Quisque eu ipsum fermentum, faucibus justo at, fringilla velit. Nam eget sem odio. Cras et dolor nec quam laoreet lacinia in vitae augue.
</p>
<br/>
<p>
	Nam at mi cursus, convallis eros non, rutrum est. Nullam in mauris auctor, sollicitudin odio eu, posuere metus. Nulla pellentesque neque quam, et venenatis nulla eleifend id. Cras eu fringilla nulla. Cras egestas vitae felis sit amet dictum. Nulla malesuada enim at sapien dictum sollicitudin. Duis lacinia, arcu vel blandit ornare, dolor velit tincidunt mauris, vel adipiscing mauris lectus at mi. Vestibulum quis lectus quis ante pellentesque aliquam. Vivamus ac erat sem. Proin elementum sapien elit, ut porta nisi euismod eu. Ut sodales est ac volutpat congue. Nullam ut sem nec eros hendrerit fermentum ac id justo.
</p>

app/views/home/get_involved.html.erb
<p>Donate</p>
<br/>
<p>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut ornare eros. Duis nisl ligula, aliquam eget bibendum eu, fermentum id lorem. Etiam cursus enim quis arcu ultrices, vitae ultricies nulla eleifend. Suspendisse eu dignissim massa. Cras ac velit urna. Ut ut ante placerat, porta velit et, dapibus elit. Ut vehicula enim purus, non semper quam posuere nec. Donec et ultricies arcu. Aenean vitae purus massa. Aenean euismod pharetra magna, ac fringilla quam fermentum non. Donec ut turpis vel lorem fringilla vulputate in nec velit.
</p>

app/views/home/index.html.erb
<div id="welcome_text">
	Welcome text !
</div>

<div id="sections">
	<%= render "home/index/section" %>
	<%= render "home/index/section" %>
	<%= render "home/index/section" %>
</div>

app/views/home/index/_section.html.erb
<div class="section">
	<div class="section_text">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>
	<div class="section_pic">
	</div>
</div>

app/views/home/issues.html.erb
<br/>
<br/>
<div class="issue" style="margin-top:   0px; margin-left: 65px"></div>
<div class="issue" style="margin-top:   0px; margin-left: 365px"></div>
<div class="issue" style="margin-top:   160px; margin-left: 65px"></div>
<div class="issue" style="margin-top:   160px; margin-left: 365px"></div>
<div class="issue" style="margin-top:   320px; margin-left: 220px"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sauba</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="main_content">
		<%= render "shared/header" %>
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_header.html.erb
<div id="header">
	<div>
		<a class="logo_link" href=<%= url_for root_path %>>
			<img src="/logo.png"/>
		</a>
		<div id="social_buttons">
			<a href="https://twitter.com/saubapac">
				<div class="social_button" id="social_button_twitter"></div>
			</a>
			<a href="https://www.facebook.com/SAUBAPAC">
				<div class="social_button" id="social_button_facebook"></div>
			</a>
			<a href="">
				<div class="social_button" id="social_button_linkedin"></div>
			</a>
			<a href="">
				<div class="social_button" id="social_button_youtube"></div>
			</a>
		</div>
	</div>
	<div id="header_menu">
		<div class="header_menu_item">
			<a href=<%= url_for about_us_path %>>
				About us
			</a>
		</div>
		<div class="header_menu_item">
			<a href=<%= url_for issues_path %>>
				Issues
			</a>
		</div>
		<div class="header_menu_item">
			<a href=<%= url_for get_involved_path %>>
				Get Involved
			</a>
		</div>
	</div>
</div>